version: '3.8'

services:
  db:
    image: postgis/postgis:16-master
    container_name: postgis-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hyh
