
### GPS 좌표로 가장 가까운 정류장 검색
GET localhost:8080/api/v1/busStations/search/nearest ? latitude=37.569808 & longitude=126.987752

### 정류소명으로 정류장 검색
GET localhost:8080/api/v1/busStations/search/stationName ? stationName=이촌

### 정류소명으로 정류장 검색(경기도)
GET localhost:8080/api/v1/busStations/search/gyeongiBus ? stationName=동탄

### 정류소 실시간 조회(경기도)
GET localhost:8080/api/v1/busStations/search/233002377/list
